

class ValueException(Exception):
    def __init__(self, message = "Ведите корректоное значение"):
        super().__init__(message)


