

class ValueException(Exception):
    def __init__(self, message = "Ведите корректоне значение"):
        super().__init__(message)


